// <auto-generated />
using System;
using EstateMapperWeb.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstateMapperWeb.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EstateMapperWeb.Models.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DetailAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("MainImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("SubRegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubRegionId");

                    b.ToTable("House");
                });

            modelBuilder.Entity("EstateMapperWeb.Models.Layout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<int>("LayoutName")
                        .HasColumnType("int");

                    b.Property<string>("LayoutUrl")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.ToTable("Layouts");
                });

            modelBuilder.Entity("EstateMapperWeb.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RegionId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RegionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RegionId");

                    b.ToTable("Regions", (string)null);

                    b.HasData(
                        new
                        {
                            RegionId = 420100,
                            Name = "武汉市"
                        },
                        new
                        {
                            RegionId = 420200,
                            Name = "黄石市"
                        },
                        new
                        {
                            RegionId = 420300,
                            Name = "十堰市"
                        },
                        new
                        {
                            RegionId = 420500,
                            Name = "宜昌市"
                        },
                        new
                        {
                            RegionId = 420600,
                            Name = "襄阳市"
                        },
                        new
                        {
                            RegionId = 420700,
                            Name = "鄂州市"
                        },
                        new
                        {
                            RegionId = 420800,
                            Name = "荆门市"
                        },
                        new
                        {
                            RegionId = 420900,
                            Name = "孝感市"
                        },
                        new
                        {
                            RegionId = 421000,
                            Name = "荆州市"
                        },
                        new
                        {
                            RegionId = 421100,
                            Name = "黄冈市"
                        },
                        new
                        {
                            RegionId = 421200,
                            Name = "咸宁市"
                        },
                        new
                        {
                            RegionId = 421300,
                            Name = "随州市"
                        },
                        new
                        {
                            RegionId = 422800,
                            Name = "恩施土家族苗族自治州"
                        },
                        new
                        {
                            RegionId = 429004,
                            Name = "仙桃市"
                        },
                        new
                        {
                            RegionId = 429005,
                            Name = "潜江市"
                        },
                        new
                        {
                            RegionId = 429006,
                            Name = "天门市"
                        },
                        new
                        {
                            RegionId = 429021,
                            Name = "神农架林区"
                        });
                });

            modelBuilder.Entity("EstateMapperWeb.Models.SubRegion", b =>
                {
                    b.Property<int>("SubRegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubRegionId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SubRegionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("SubRegionId");

                    b.HasIndex("RegionId");

                    b.ToTable("SubRegions", (string)null);

                    b.HasData(
                        new
                        {
                            SubRegionId = 420101,
                            Name = "江岸区",
                            RegionId = 420100
                        },
                        new
                        {
                            SubRegionId = 420102,
                            Name = "江汉区",
                            RegionId = 420100
                        },
                        new
                        {
                            SubRegionId = 420103,
                            Name = "硚口区",
                            RegionId = 420100
                        },
                        new
                        {
                            SubRegionId = 420104,
                            Name = "汉阳区",
                            RegionId = 420100
                        },
                        new
                        {
                            SubRegionId = 420105,
                            Name = "武昌区",
                            RegionId = 420100
                        },
                        new
                        {
                            SubRegionId = 420106,
                            Name = "青山区",
                            RegionId = 420100
                        },
                        new
                        {
                            SubRegionId = 420107,
                            Name = "洪山区",
                            RegionId = 420100
                        },
                        new
                        {
                            SubRegionId = 420108,
                            Name = "东西湖区",
                            RegionId = 420100
                        },
                        new
                        {
                            SubRegionId = 420109,
                            Name = "汉南区",
                            RegionId = 420100
                        },
                        new
                        {
                            SubRegionId = 420110,
                            Name = "蔡甸区",
                            RegionId = 420100
                        },
                        new
                        {
                            SubRegionId = 420111,
                            Name = "江夏区",
                            RegionId = 420100
                        },
                        new
                        {
                            SubRegionId = 420112,
                            Name = "黄陂区",
                            RegionId = 420100
                        },
                        new
                        {
                            SubRegionId = 420113,
                            Name = "新洲区",
                            RegionId = 420100
                        },
                        new
                        {
                            SubRegionId = 420201,
                            Name = "黄石港区",
                            RegionId = 420200
                        },
                        new
                        {
                            SubRegionId = 420202,
                            Name = "西塞山区",
                            RegionId = 420200
                        },
                        new
                        {
                            SubRegionId = 420203,
                            Name = "下陆区",
                            RegionId = 420200
                        },
                        new
                        {
                            SubRegionId = 420204,
                            Name = "铁山区",
                            RegionId = 420200
                        },
                        new
                        {
                            SubRegionId = 420205,
                            Name = "阳新县",
                            RegionId = 420200
                        },
                        new
                        {
                            SubRegionId = 420206,
                            Name = "大冶市",
                            RegionId = 420200
                        },
                        new
                        {
                            SubRegionId = 429004,
                            Name = "仙桃市",
                            RegionId = 429004
                        },
                        new
                        {
                            SubRegionId = 429005,
                            Name = "潜江市",
                            RegionId = 429005
                        },
                        new
                        {
                            SubRegionId = 429006,
                            Name = "天门市",
                            RegionId = 429006
                        },
                        new
                        {
                            SubRegionId = 429021,
                            Name = "神农架林区",
                            RegionId = 429021
                        });
                });

            modelBuilder.Entity("EstateMapperWeb.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HouseId")
                        .HasColumnType("int");

                    b.Property<string>("TagName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("EstateMapperWeb.Models.House", b =>
                {
                    b.HasOne("EstateMapperWeb.Models.SubRegion", null)
                        .WithMany("Houses")
                        .HasForeignKey("SubRegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EstateMapperWeb.Models.Layout", b =>
                {
                    b.HasOne("EstateMapperWeb.Models.House", null)
                        .WithMany("Layouts")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EstateMapperWeb.Models.SubRegion", b =>
                {
                    b.HasOne("EstateMapperWeb.Models.Region", "Region")
                        .WithMany("SubRegions")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("EstateMapperWeb.Models.Tag", b =>
                {
                    b.HasOne("EstateMapperWeb.Models.House", null)
                        .WithMany("Tags")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EstateMapperWeb.Models.House", b =>
                {
                    b.Navigation("Layouts");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("EstateMapperWeb.Models.Region", b =>
                {
                    b.Navigation("SubRegions");
                });

            modelBuilder.Entity("EstateMapperWeb.Models.SubRegion", b =>
                {
                    b.Navigation("Houses");
                });
#pragma warning restore 612, 618
        }
    }
}
